### ISSUE TITLE
not working on mac - cannot authentificate

### ISSUE THREAD

**Issue by jsavalle** [YuheiNakasaka/vue-twitter-client#1]
<img width="776" alt="screen shot 2018-03-26 at 15 25 44" src="https://user-images.githubusercontent.com/5922799/37908985-fc9bf476-3109-11e8-94b8-3a2b5dca082b.png">

**Comment by YuheiNakasaka** [comment]
@jsavalle You need to set your `consumer key` and `cosumer secret` at this line.
https://github.com/YuheiNakasaka/vue-twitter-client/blob/master/app/src/main/authentication-window.js#L10

To get a consumer key and consumer secret, read [this](https://stackoverflow.com/questions/1808855/getting-new-twitter-api-consumer-and-secret-keys).

**Comment by jsavalle** [comment]
thanks... I assume that was the issue.
I'll package it from the source.
I just thought there is a way to make the package work.

**Comment by YuheiNakasaka** [comment]
Sorry for confusing you...

I'll write it to README 👍
